name: Tests
on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      
      - uses: Swatinem/rust-cache@v2
      
      - name: Run Clippy
        run: |
          cargo clippy --all-targets --all-features -- -D warnings || true
        continue-on-error: true

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: dtolnay/rust-toolchain@stable
      
      - uses: Swatinem/rust-cache@v2
      
      - name: Build Project
        run: |
          cargo build --verbose || true
        continue-on-error: true
      
      - name: Run Tests
        run: |
          cargo test --all --verbose || true
        continue-on-error: true
